### ISSUE TITLE
`make test` could not be passed.

### ISSUE THREAD

**Issue by makki547** [dacase/afnmr#1]
I'm now trying to use this AFNMR to calculate chemical shifts of a small peptide. 
`make` has been successfully done, but `make test` could not be passed.

In `1d3z_test3`, the test is terminated in minimization step with following message;
>Error in txmin: check 1d3z1.min.o

It looks `txmin` runs, because the test runs to the end without any problems when the error is ignored by following modification;

```diff
--- afnmr	2021-05-19 17:29:12.697586833 +0900
+++ afnmr.mod	2021-05-19 17:32:09.877004267 +0900
@@ -193,10 +193,10 @@
 
 $AFNMRHOME/bin/txmin $1.parm7 $1.x $1.min.x > $1.min.o
 
-if [ "$?" -gt 0 ]; then 
-   echo "Error in txmin: check $1.min.o"
-   exit 1
-fi
+#if [ "$?" -gt 0 ]; then 
+#   echo "Error in txmin: check $1.min.o"
+#   exit 1
+#fi
 echo "====== min.o =========================================================" \
      >> $1.afnmr.log
 cat $1.min.o >> $1.afnmr.log
```

Output of `txmin` is attached;
[1d3z1.min.o.txt](https://github.com/dacase/afnmr/files/6507472/1d3z1.min.o.txt)

I don't have any idea for the reason. Do you have any idea?

**Comment by dacase** [comment]
Thanks for the report.  The minimization file looks correct, so I can't see why the exit value for txmin would be non-zero.
Can you say what OS and compiilers you are using?

You could try adding a print statement at the end of `txmin.c` to see if it is actually getting to the end of code.  It's possible that some error exit is being triggered inside the libsff routines that are being called.

However, if the tests pass with your modifcation, you should be able to continue with your work.

**Comment by makki547** [comment]
Thanks for your rapid response, Prof. Case.

The OS is CentOS Linux release 7.6.1810 and compilers are gcc 4.8.5.
Return code of txmin in the test is 243.

Anyway, I continue my work with the modification.
