### ISSUE TITLE
Error in atom type

### ISSUE THREAD

**Issue by zlcrrrr** [dacase/afnmr#10]
Dear Prof. Case,

When I run AFNMR for residue 27 in a PDB file using the command 

```
$AFNMRHOME/bin/afnmr -nomin -list "27" -orca test
```

it will give an error, 

```
Running AFNMR on test.pdb
Running tleap
Skipping minimization
afnmr.x O D F OLYP 3.3 test 27
 error in solinprot: check solinprot.out
 error code was            1
 command line was:
 ./runsolinprot test027
STOP 1
Error in afnmr: check afnmr.out
```

I am attaching the PDB file. Is it a bug? Thanks.

[test.pdb.zip](https://github.com/dacase/afnmr/files/11252378/test.pdb.zip)

**Comment by dacase** [comment]
Works for me.  Can you provide any other files that were created?  test027.*, test.afnmr.log would help.  Check that you are up to date with the git repository, and let me know what OS and compilers you are using.

**Comment by zlcrrrr** [comment]
OS: Rocky Linux 8.6 (Green Obsidian)
Compilers: gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)

I am attaching test.* 

[test.zip](https://github.com/dacase/afnmr/files/11254002/test.zip)

Thank you.

**Comment by dacase** [comment]
This is indeed a bug: you seem to have found the first example where more than 9 extra hydrogens need to be added to a fragment as link atoms.

I've pushed what should be a fix; do `git pull` followed by `make install`.  Then try your test case again -- it seems to be working for me.

Thanks for the report.

**Comment by zlcrrrr** [comment]
It works perfectly for me. Thank you very much!
