### ISSUE TITLE
Adjust dielectric constants

### ISSUE THREAD

**Issue by zlcrrrr** [dacase/afnmr#2]
Dear Prof. Case,

Would you please let me know how to adjust dielectric constant in AFNMR to calculate CS at a low temperature? I tried to add the -epsext flag in the _solinprot_ related line,

> $AFNMRHOME/bin/solinprot -epsin1 1.0 -epsin2 4.0 **-epsext 100.0** -ionicstr 0.2 -ProteinField -ReactionField \$1 \$1.prot

but the CS calculation result is the same, though some point charges in the *.pos file are different. 

Thanks,
Lichirui

**Comment by dacase** [comment]
On Wed, Dec 01, 2021, Lichirui Zhang wrote:
>
>Would you please let me know how to adjust dielectric constant in AFNMR to
>calculate CS at a low temperature? I tried to add the -epsext flag in the
>_solinprot_ related line,
>
>> $AFNMRHOME/bin/solinprot -epsin1 1.0 -epsin2 4.0 **-epsext 100.0**
>> -ionicstr 0.2 -ProteinField -ReactionField \$1 \$1.prot
>
>but the CS calculation result is the same, though some point charges in the
>*.pos file are different.

This sounds about right: the difference between epsext=80 and epsext=100 is
very small-- remember that the key influence goes like (1 -1/eps).  I would
guess that any real temperature dependence of chemical shifts is arising
from something other than the solvent dielectric.

....good luck....dac

**Comment by zlcrrrr** [comment]
Thank you
