### ISSUE TITLE
Getting error while creating Fragments for my Protein

### ISSUE THREAD

**Issue by LakhwinderSingh1999** [dacase/afnmr#3]
I wanted to create Fragments of my protein using afnmr. But i am getting this error message. Kindly Help me in solving this issue

[admin@nmrmkp MSI594_clean]$  ~/afnmr/bin/afnmr -list Protein.pdb "{5..8}"                         
Running AFNMR on {5..8}.pdb
Running tleap
Error in tleap: check tleap.out or leap.log

[tleap-out-file.txt](https://github.com/dacase/afnmr/files/8332021/tleap-out-file.txt)
[leap-log-file.txt](https://github.com/dacase/afnmr/files/8332022/leap-log-file.txt)

**Comment by dacase** [comment]
The argument to `-list` has to come right after the flag itself:
```
~/afnmr/bin/afnmr -list "{5..8}" Protein.pdb
```
See if that helps...dac
