### ISSUE TITLE
Problem in surface chargues 

### ISSUE THREAD

**Issue by israelsech** [dacase/afnmr#4]
I tried running the test files. The input files were created but for some reason the results are not the same as the example files. The coordinates of the surface chargues computed using the PS equation are the same, but the value of chargues are quite different. 
Any idea of why this is happening? Thanks!

[1d3z1003.com.txt](https://github.com/dacase/afnmr/files/8341556/1d3z1003.com.txt)
[1d3z1.afnmr.log.txt](https://github.com/dacase/afnmr/files/8341557/1d3z1.afnmr.log.txt)
[1d3z1003.com.save.txt](https://github.com/dacase/afnmr/files/8341563/1d3z1003.com.save.txt)

**Comment by dacase** [comment]
I have pushed an update to make the version numbers and formats in the .save files match the current code.

But that doesn't address your results, which I am not able to reproduce.  Can you say what operating system and compilers you are using?

**Comment by israelsech** [comment]
I am using an Ubuntu 20.04.3 LTS with:
gcc  9.4.0
g++  9.4.0
GNU Make 4.2.1

**Comment by dacase** [comment]
Odd.  I am using gcc 9.4.0 on Ubuntu 18.04.  My Gaussian test case (and all the other test cases) PASS.

Do you get errors only with the Gaussian test case?  But I'm grasping at straws here.  Do you have access to any other machine that you could try?

**Comment by israelsech** [comment]
I get the same chargue values with Demon option. I have also the PASS but with possible FAILURE in all tests. I tried in my personal computer, but it has the same configuration that the computer in my laboratory, and I get the same results. I will try tomorrow with others available computers in my laboratory.

**Comment by israelsech** [comment]
Hi!

I tried other machine with Ubuntu 20.04.4 LTS and the same compilers. It works perfect. If I manage to solve the problem with the first machine, I will post here.

Thanks for you help!
