### ISSUE TITLE
Dealing with modified residues

### ISSUE THREAD

**Issue by aminsagar** [dacase/afnmr#5]
Hello.
Thanks for making this program available.
I am trying to use it with a modified amino acid i.e., Fluoroglutamine.
I parameterized it and created  the FRCMOD files.
I then edited the afnmr file to add the following lines

cat > leap.in << EOF
source leaprc.protein.ff14SB
source leaprc.phosaa14SB
source leaprc.RNA.OL3
source leaprc.DNA.OL15
source leaprc.water.tip3p
source leaprc.gaff2
set default PBRadii mbondi3
**loadAmberParams FlQ21.frcmod
loadAmberParams FlQ_MRP.frcmod
GL1 = loadmol2 GL1.mol2**
EOF

cat <<EOF >> leap.in
set default nocenter on
set default reorder_residues off
x = loadpdb $1.pdb
**bond x.20.C x.21.N
bond x.21.C x.22.N**
$afterloadpdb
saveamberparm x $1.parm7 $1.x
quit
EOF

This gives correct complete pqr files, but the fragment pqr files have duplicated N atom of the modified residue. For example,
```
ATOM    336  O   GLN    20      26.561  22.217 -27.062 -0.5679   1.500       O
ATOM    337  N   GL1    21      27.452  23.905 -25.826 -0.3410   1.550       N
ATOM    337  N   GL1    21      27.452  23.905 -25.826 -0.3410   1.550       N
ATOM    338  H   GL1    21      28.312  24.413 -25.628  0.1942   1.300       H
```
I get a warning about this and the program gives me an error as follows.
```
WARNING: AtomSet::read: Input file, test020.pqr,
contains duplicate entries for the atom, N:21:N.
Last one will override previous
AtomSet::read: attempt to insert a duplicate atom

terminate called after throwing an instance of 'MEADexcept'
./runsolinprot: line 19: 26135 Aborted                 (core dumped) /path/afnmr1.5/afnmr/bin/solinprot -epsin1 1.0 -epsin2 4.0 -ionicstr 0.2 -ProteinField -ReactionField $1 $1.prot
 error in solinprot: check solinprot.out
 error code was            1
 command line was:
 ./runsolinprot test020
STOP 1
Error in afnmr: check afnmr.out
```
If I manually remove the duplicated atom, I can run solinprot.
What can I do to make afnmr correctly process with the modified residue?
I would be really grateful for any suggestions.

Amin.

**Comment by aminsagar** [comment]
Update ..
I added the modified residue to "presn" in afnmr.F90 file and the program runs without any error.
```
integer, parameter ::MAXNRES=33,MAXPRES=42
...
...
presn(40) = 'H1E'
presn(41) = 'H2E'
presn(42) = 'GL1'
```

**Comment by dacase** [comment]
On Sun, May 29, 2022, aminsagar wrote:

>I added the modified residue to "presn" in afnmr.F90 file and the program runs without any error.
>```
>integer, parameter ::MAXNRES=33,MAXPRES=42
>...
>...
>presn(40) = 'H1E'
>presn(41) = 'H2E'
>presn(42) = 'GL1'
>```
>

Thanks for the report and for figuring this out.  I need to update the instructions on what one
has to do with modified residues.

....dave case
