### ISSUE TITLE
Error in tleap for getting fragments

### ISSUE THREAD

**Issue by KetanR24** [dacase/afnmr#6]
Hello there,
I hope you are doing well. I am using AFNMR to get fragments for my pdb files. But I am facing tleap errors about atom names. e.g.
FATAL: Atom .R<IPH 308>.A<C1 1> does not have a type.
FATAL:  Atom .R<NGLY 1>.A<HN 10> does not have a type.
FATAL:  Atom .R<ILE 2>.A<HN 20> does not have a type.
FATAL:  Atom .R<VAL 3>.A<HN 17> does not have a type.
FATAL:  Atom .R<GLU 4>.A<HN 16> does not have a type.
FATAL:  Atom .R<GLN 5>.A<HN 18> does not have a type.
FATAL:  Atom .R<CYX 6>.A<HN 11> does not have a type.
FATAL:  Atom .R<CYX 7>.A<HN 11> does not have a type.
FATAL:  Atom .R<THR 8>.A<HN 15> does not have a type.
FATAL:  Atom .R<SER 9>.A<HN 12> does not have a type.
FATAL:  Atom .R<ILE 10>.A<HN 20> does not have a type.

Kindly help me to overcome these errors. How can I modify my pdb file in amber format and what if some organic molecules like phenol are present in my structure? How to deal with them? I have been searching for solutions online but I could not find any.
[leap.log](https://github.com/dacase/afnmr/files/9082492/leap.log)
[leap.log](https://github.com/dacase/afnmr/files/9082492/leap.log)
[leap.log](https://github.com/dacase/afnmr/files/9082496/leap.log)
[leap.log](https://github.com/dacase/afnmr/files/9082496/leap.log)

**Comment by dacase** [comment]
On Mon, Jul 11, 2022, KetanR24 wrote:

>I hope you are doing well. I am using AFNMR to get fragments for my pdb
>files. But I am facing tleap errors about atom names. e.g.

>FATAL: Atom .R<IPH 308>.A<C1 1> does not have a type.

If you have ligands, you will need to become familiar with the Amber
procedure for generating paramters for them.  A tutorial is here:

    https://ambermd.org/tutorials/basic/tutorial4b/index.php

Then you can use the -offlib and -frcmod flags in afnmr to load the
parameters for your ligand.

>FATAL:  Atom .R<NGLY 1>.A<HN 10> does not have a type.
>FATAL:  Atom .R<ILE 2>.A<HN 20> does not have a type.
>

Your input pdb file is using very outdated hydrogen atom names.  The
PDB/IUPAC standard says the amide protons should be named "H", execpt on
protonate N-termini (e.g. NGLY) where the names are "H1", "H2", "H3".

A note: you are using a very big protein, with many chains.  Try starting
with simpler systems to see how things work.  I think you may need to put
all the IPH residues at the end of the input pdb file.

....hope this helps...dac
