### ISSUE TITLE
reference shifts file or file format (documentation problem?)

### ISSUE THREAD

**Issue by HowardBroughton** [dacase/afnmr#7]
make-shiftsrdb is described in the documentation as requiring the program used and basename of the (in my case gaussian) QM output files.   However, on attempting to run it it also requests a "reference shifts" dataset, but I have been unable to find either a suitable file for shifts computed using the default basis set in afnmr 1.3 or 1.6 installations (or indeed any basis set), or the format for the file or how to generate it from calculated data for whatever reference standard compounds.   Could you please let me know where I should go for this info?  Many thanks!

**Comment by HowardBroughton** [comment]
Just realized the documentation states that the underlying parsers are in perl, so having edited those, I can see the options for the reference shifts and how to apply them.   Perhaps just a quick update to the documentation and the make-shiftsrdb would help here!  Thanks very much for putting this stuff on github!

**Comment by dacase** [comment]
On Mon, Sep 05, 2022, HowardBroughton wrote:

>Just realized the documentation states that the underlying parsers
>are in perl, so having edited those, I can see the options for the
>reference shifts and how to apply them.  Perhaps just a quick update to the
>documentation and the make-shiftsrdb would help here!  Thanks very much for
>putting this stuff on github!

Thanks for your note.  I've pushed updated documentation (in both the .pdf
file, and in the make-shiftsrdb script itself) to github.

...thanks...dac

-- 

====================================================================
David A. Case                         |       ***@***.***
Dept. of Chemistry & Chemical Biology |
Rutgers University                    |   skype:              dacase
174 Frelinghuysen Road, Rm. 208b      |   cell:      +1-609-751-8668
Piscataway, NJ 08854        USA       |   web: casegroup.rutgers.edu
====================================================================

**Comment by HowardBroughton** [comment]
Thanks David!   Beginning to get some interesting results with this toolkit.

Very much appreciate your help and response to my suggestion!

Best,

Howard.

From: David A Case ***@***.***>
Sent: Tuesday, October 11, 2022 10:48 AM
To: dacase/afnmr ***@***.***>
Cc: Howard Broughton ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [dacase/afnmr] reference shifts file or file format (documentation problem?) (Issue #7)


EXTERNAL EMAIL: Use caution before replying, clicking links, and opening attachments.

On Mon, Sep 05, 2022, HowardBroughton wrote:

>Just realized the documentation states that the underlying parsers
>are in perl, so having edited those, I can see the options for the
>reference shifts and how to apply them. Perhaps just a quick update to the
>documentation and the make-shiftsrdb would help here! Thanks very much for
>putting this stuff on github!

Thanks for your note. I've pushed updated documentation (in both the .pdf
file, and in the make-shiftsrdb script itself) to github.

...thanks...dac

--

====================================================================
David A. Case | ***@***.***
Dept. of Chemistry & Chemical Biology |
Rutgers University | skype: dacase
174 Frelinghuysen Road, Rm. 208b | cell: +1-609-751-8668
Piscataway, NJ 08854 USA | web: casegroup.rutgers.edu
====================================================================
