### ISSUE TITLE
Use different water model in AFNMR

### ISSUE THREAD

**Issue by zlcrrrr** [dacase/afnmr#8]
Dear Prof. Case,

Would you please give me a hint on how to switch the water model used in AFNMR from TIP3P to a different one, say TIP4P-EW?

Thanks!

**Comment by dacase** [comment]
If you want to do this for all projects, go to the src/afnmr folder, and edit the "afnmr" file there.  At about line 94,
change "leaprc.water.tip3p" to "leaprc.water.tip4pew".  Then type "make install" to get this file put into the afnmr/bin folder.

Note that I don't expect much to change.  All afnmr is doing (that depends on the force field,) is a very few steps of minimization, to remove bad contacts and to regularize bond lengths.  So, even if tip4pew prefers a different hydrogen bond geometry, the input files to the quantum program will be almost unchanged. (Of course: experiment to see if I'm correct here.)

Above assumes that your input PDB file already has water molecules.  You need different sorts of software (such as AmberTools itself) to add and optimize waters.  Such procedures will depend on the force field used.  But a further caution: forcefields like tip3p and tip4pew describe bulk water well, but they are not flexible enough to do a great job on hydrogen bonding between solutes and water (which can be key for chemical shifts).  The best way to handle solvent is still an unsolved problem (at least in my view.)

....hope this helps....dac

**Comment by zlcrrrr** [comment]
Thanks for your comment! I got another error "MS Error in atom type Error in ms: check afnmr.log". I guess it's because it cannot identify the "EPW" virtual atom in tip4pew.

**Comment by dacase** [comment]
I've pushed a fix which should fix the problem: do a git pull and re-install.  (I still think that this is unlikely to do any real good, as outlined above.

**Comment by zlcrrrr** [comment]
Thank you very much. This is really helpful!
